kind: YttTemplate
apiVersion: apps/v1
metadata:
  name: amf-template-day1
template:
  #@ day1 = data.values.day1
  data:
    coreamffunction:
      servedGuamiList:
        #@ for networkFunction in day1.coreamffunction.servedGuamiList:
        - sectorId: #@ networkFunction.sectorId
          id: #@ networkFunction.id
          name: #@ networkFunction.name
          pci: #@ networkFunction.pci
          tac: #@ networkFunction.tac
          #@ end
#@ end
