kind: YttTemplate
apiVersion: apps/v1
metadata:
  name: cns-template-upf
template:
  #@ load("@ytt:math","math")
  #@ day0 = data.values.day0
  #@ day1 = data.values.day1
  day0:
    #@ if day0.resilience.high_availability:
    #@   min_instances = 2
    #@ else:
    #@   min_instances = 1
    #@ end
    user_instances: #@ max ( math.floor( (day0.capacity.maxNFConnection-1) / 1000) + 1, min_instances)
    networkFunction_instances: #@ max ( math.floor( (day0.capacity.maxSessions-1) / 256) + 1, min_instances)
  day1:
    free5gcupffunction:
      n_networkFunction:
        #@ for networkFunction in day1.maxSessions:
        - id: #@ networkFunction.id
          name: #@ networkFunction.name
          pci: #@ networkFunction.pci
          tac: #@ day1.common.tac
          #! nb
      #@ end
