kind: YttTemplate
apiVersion: apps/v1
metadata:
  name: site-schema
schema:
  day0:
    capacity:
      #!
      #@schema/desc "amf capacity in number of connected users"
      #@schema/validation min=100,max=10000
      #!
      connected_users: -1
      #!
      #@schema/validation min=1,max=2048
      #@schema/desc "amf capacity in number of cells"
      #!
      cells: -1
      #!
      #@schema/validation min=1,max=2048
      #@schema/desc "amf capacity in number of average user throughput in MB/s"
      #!
      user_throughput: -1.0
    resilience:
      #!
      #@schema/desc "high availability requires amf to be redundant, i.e. instances > 1"
      #!
      high_availability: no
  day1:
    common:
      tac: 0
      mcc: 25
      mnc: 21
    cells:
      - id: 0
        sectorId: 0
        pci: 0
        name: ""
