kind: YttTemplate
apiVersion: apps/v1
metadata:
  name: site-template-amf
template:
  #@ load("@ytt:math","math")
  #@ day0 = data.values.day0
  #@ day1 = data.values.day1
  day0:
    instances: #@ math.floor( (day0.capacity.maxSessions-1) / 128) + 1
  day1:
    coreamffunction:
      servedGuamiList:
        #@ for networkFunction in day1.maxSessions:
        - id: #@ networkFunction.id
          name: #@ networkFunction.name
          pci: #@ networkFunction.pci
          tac: #@ day1.common.tac
          #! nb
      #@ end
