kind: YttTemplate
apiVersion: apps/v1
metadata:
  name: site-ciq
#! -----------------------------------------
#! Describes a site consisting of a parts of a core
#!
#! The free5gc consists of amf + smf + upf
#! -----------------------------------------
values:
  #! ----------------------------------------
  #! Describes initial software configuration
  #! ----------------------------------------
  day0:
    capacity:
      maxNFConnection: 50
      maxSessions: 2048
      subscribedUe: 2.5
    resilience:
      high_availability: true
  #! -------------------------------------
  #! Describes initial day 1 configuration
  #! -------------------------------------
  day1:
    common:
      mcc: 23
      mnc: 11
      tac: 38
    maxSessions:
      - id: 100
        sectorId: 0
        pci: 33
      - id: 102
        sectorId: 1
        pci: 38
