kind: YttTemplate
apiVersion: apps/v1
metadata:
  name: site-template-amf
template:
  #@ load("@ytt:math","math")
  #@ day0 = data.values.day0
  #@ day1 = data.values.day1
  day0:
    instances: #@ math.floor( (day0.capacity.cells-1) / 128) + 1
  day1:
    coreamffunction:
      servedGuamiList:
        #@ for cell in day1.cells:
        - id: #@ cell.id
          name: #@ cell.name
          pci: #@ cell.pci
          tac: #@ day1.common.tac
          #! nb
      #@ end
